name: moodly

services:
  postgres:
    image: postgres:17
    container_name: moodlydb
    environment:
      POSTGRES_DB: moodlydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7.4-alpine
    container_name: redis_server
    command: redis-server --requirepass 123456789 --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

  kafka:
    image: apache/kafka:latest
    container_name: moodly-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
    restart: unless-stopped

  # app:
  #   image: ghcr.io/khanakorn-k/moodlybackend:latest
  #   container_name: moodly-app
  #   depends_on:
  #     - postgres
  #     - redis
  #     - kafka
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     DB_HOST: postgres
  #     REDIS_HOST: redis
  #     KAFKA_HOST: kafka
  #   restart: unless-stopped

volumes:
  postgres_data:
  redis_data: