name: Go CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - name: Download Dependencies
        run: go mod download

      - name: Check Go Format
        run: |
          diffs=$(gofmt -l .)
          if [ -n "$diffs" ]; then
            echo "The following files need formatting:"
            echo "$diffs"
            exit 1
          fi

      - name: Go Vet
        run: go vet ./...

      - name: Run Tests
        run: go test -v ./...

      - name: Build
        run: go build -v ./...

      - name: Install Swag
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Generate Swagger
        run: make swagerinit

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      #  บังคับให้มันชื่อเป็นตัว lowercase
      - name: Set image name
        run: |
          echo "IMAGE_NAME=$(echo ghcr.io/${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:${{ github.sha }} \
            -f Docker/dockerfile .

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
