name: Moodly CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.26"
          cache: true

      - name: Download modules
        run: go mod download

      - name: Test
        run: go test ./...

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build ./...

  build-image:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image
        run: echo "IMAGE=${REGISTRY}/${IMAGE_NAME,,}" >> $GITHUB_ENV

      - name: Build image
        run: |
          docker build \
            -f Docker/dockerfile \
            -t $IMAGE:latest \
            -t $IMAGE:${{ github.sha }} .

      - name: Push image
        run: |
          docker push $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}

  deploy:
    needs: build-image
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        env:
          IMAGE_TAG: ${{ github.sha }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          URL_SERVER: ${{ secrets.URL_SERVER }}
          KAFKA_ADDR: ${{ secrets.KAFKA_ADDR }}

        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}

          envs: IMAGE_TAG,GITHUB_ACTOR,GITHUB_TOKEN,DATABASE_URL,REDIS_PASSWORD,JWT_SECRET,URL_SERVER,KAFKA_ADDR

          script: |
            set -e

            echo "$GITHUB_TOKEN" | docker login ghcr.io \
              -u "$GITHUB_ACTOR" \
              --password-stdin

            if [ ! -d ~/moodly ]; then
              git clone https://github.com/Khanakorn-K/moodlybackend.git ~/moodly
            fi

            cd ~/moodly
            git fetch origin
            git reset --hard origin/main

            cd Docker

            cat > .env <<EOF
            IMAGE_TAG=$IMAGE_TAG
            DATABASE_URL=$DATABASE_URL
            REDIS_PASSWORD=$REDIS_PASSWORD
            JWT_SECRET=$JWT_SECRET
            URL_SERVER=$URL_SERVER
            KAFKA_ADDR=$KAFKA_ADDR
            EOF

            docker compose pull

            docker compose up -d

            until docker compose exec -T postgres pg_isready -U postgres -d moodlydb
            do
              sleep 2
            done

            docker compose exec -T app \
              go run config/migrate/migrate.go

            docker image prune -af